baseURL: https://omidshenavar.github.io/
languageCode: en-us
build:
  writeStats: true

params:
  title: Omid Shenavar - Academic Resume
  author: Omid Shenavar
  description: Omid Shenavar's Academic Resume Website
  copyright:  "Powered by [Hugo](https://gohugo.io/)"
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Omid Shenavar"
    tagline: "Plant Pathologist & Bioinformatician"
    location: "Shiraz, Iran"
    photo: profile.jpg
  social:
    title: Academic Profiles
    list:
      - icon: ai ai-orcid
        url: "https://orcid.org/0000-0003-2297-8352"
        title: ORCID
      - icon: ai ai-researchgate
        url: "https://www.researchgate.net/profile/Omid-Shenavar"
        title: ResearchGate
      - icon: ai ai-google-scholar
        url: "https://scholar.google.com/citations?user=Uvse3ykAAAAJ&hl=en&oi=ao"
        title: Google Scholar
      - icon: fab fa-linkedin-in
        url: "https://ir.linkedin.com/in/omid-shenavar-46702496"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/omidshenavar"
        title: GitHub
      - icon: fas fa-bold
        url: "https://bsky.app/profile/omidshenavar.bsky.social"
        title: Bluesky
  showInAccordion:
    - item: aboutme
      expand: true
    - item: education
    - item: experience
    - item: publication
    - item: skill
    - item: hobby
    - item: contactme
    - item: downloadcv
  aboutme:
    title: About Me
    icon: fas fa-user
    description: >
      I am a passionate plant pathologist specializing in bacterial pathogens, with expertise in *Xanthomonas* species. My work spans bioinformatics, molecular phylogeny, and plant-microbe interactions. I currently manage a pharmacy while consulting in research and translation, supporting students and researchers with bioinformatics analyses, scientific writing, and translations for international journals.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: M.Sc. in Plant Pathology (Phytobacteriology)
        college: Sari Agricultural Sciences and Natural Resources University (SANRU)
        dates: September 2014 - September 2017
        details: |
          - Studied under Professor Heshmat Rahimian supervision, focusing on plant pathogenic bacteria.
          - Contributed to the Plant Pathology Association magazine.
      - degree: B.Sc. in Plant Protection
        college: Shiraz University
        dates: September 2010 - August 2014
        details: |
          - Member of the Editorial Board of the Plant Protection Association.
          - Coordinated the Scientific Seminar on Evolution.
  experience:
    title: Professional Experience
    icon: fas fa-briefcase
    list:
      - position: Pharmacy Manager
        company: Dr. Ghassami Pharmacy
        dates: 2019 - Present
        details: |
          - Manage operations, staff training, and ensure health regulation compliance.
          - Implement process improvements for customer satisfaction.
      - position: Freelance Writer, Consultant, and Translator
        dates: 2017 - Present
        details: |
          - Provide consulting, writing, and bioinformatics analyses for academic projects.
          - Translate scientific manuscripts for international journal publications.
      - position: IT Support Assistant (Student Employment)
        company: SANRU
        dates: 2014 - 2016
        details: |
          - Supported university IT operations, troubleshooting hardware and software.
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Conference Papers
    list:
      - title: "Leaf Spot and Stem Canker of Pistachio Trees Incited by Xanthomonas Strains"
        authors: "Maryam Khorasani, Akbar Hosseinipour, Omid Shenavar, Heshmat Rahimian"
        date: "May 2025"
        journal: "Journal of Phytopathology"
        url: "https://doi.org/10.1111/jph.70078"
        type: Journal Articles      
      - title: "Characterization of Xanthomonas hortorum isolates causing leaf spot on Primula vulgaris"
        authors: "Omid Shenavar, Heshmatolah Rahimian, Ali Barzegar"
        date: "July 2023"
        journal: "Plant Pathology"
        url: "http://dx.doi.org/10.1111/ppa.13782"
        type: Journal Articles
      - title: "Multi Locus Sequence Analysis of Candidatus liberibacter asiaticus Isolates in Iran"
        authors: "Siavash Samavi, Mohammad Mehdi Faghihi, Abdolnabi Bagheri, Valiollah Babaeizad, Omid Shenavar, Mohsen Amiri Mazraie"
        date: "2022"
        journal: "24th Iranian Plant Protection Congress"
        url: https://24ippc.areeo.ac.ir/paper?manu=8328
        type: Conference Papers
      - title: "Investigation of Pathogenicity and Molecular Characteristics of Staphylococcus Strains Causing Bacterial Canker in Central Iran"
        authors: "Esmaeil Asadi, Heshmatolah Rahimian, Omid Shenavar, Valiollah Babaeizad, S. Mohamad Alavi"
        date: "2018"
        journal: "Proceedings of the International Congress of Science and Engineering"
        url: "https://civilica.com/doc/755249"
        type: Conference Papers
      - title: "Isolation, Identification, and Phenotypic-Biochemical Characterization of Staphylococcus warneri Strains, the Causative Agents of Bacterial Canker in Iran"
        authors: "Esmaeil Asadi, Heshmatolah Rahimian, Omid Shenavar, Valiollah Babaeizad, S. Mohamad Alavi"
        date: "2018"
        journal: "Proceedings of the International Congress of Science and Engineering"
        url: "https://civilica.com/doc/755250"
        type: Conference Papers
      - title: "Phenotypic, Molecular, and Pathogenicity Investigation of Xanthomonas Strains Causing Primula Leaf Spot"
        authors: "Omid Shenavar, Heshmatolah Rahimian, Ali Barzegar"
        date: "2017"
        journal: "First International Symposium on Applied Research in Agricultural Sciences, Natural Resources, and Environment"
        url: "https://civilica.com/doc/673977"
        type: Conference Papers
      - title: "First report of leaf spot caused by Colletotrichum coccodes on Viola tricolor in Iran."
        authors: "T. Karamnejadi, A. Solhizadeh, O. Shenavar, M.A. Tajick-Ghanbari"
        date: "2017"
        journal: "Journal of Plant Pathology"
        volume: "99"
        number: "2"
        url: "https://www.sipav.org/en/16/Archive/3858"
        type: Journal Articles
      - title: "Molecular Identification and Taxonomic Position of Xanthomonas Strains Causing Bacterial Leaf Spot in Primula Based on gltA Gene Sequence Analysis"
        authors: "Omid Shenavar, Heshmatolah Rahimian, Ali Barzegar"
        date: "2017"
        journal: "First International Symposium on Applied Research in Agricultural Sciences, Natural Resources, and Environment"
        url: "https://civilica.com/doc/673976"
        type: Conference Papers
      - title: "Computerized Interactive Keys for Identification of Fungi"
        authors: "Omid Shenavar, Mostowfizadeh-Ghalamfarsa Reza"
        date: "2015"
        journal: "Plant Pathology Science"
        volume: "4"
        number: "2"
        url: "http://yujs.yu.ac.ir/pps/article-1-90-en.html"
        type: Journal Articles
  skill:
    title: Skills and Languages
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Molecular Phylogeny
        skillrating: 80
      - skill: Bioinformatics & MLSA
        skillrating: 80
      - skill: Pathogenicity Assays
        skillrating: 75
      - skill: Laboratory Techniques (PCR, DNA/Protein Extraction)
        skillrating: 80
      - skill: Python & R Programming
        skillrating: 60
      - skill: Linux & Open Source
        skillrating: 80
      - skill: Scientific Writing & Editing
        skillrating: 85
      - skill: Project Management & Leadership
        skillrating: 80
      - skill: English (IELTS 7.5)
        skillrating: 75
  hobby:
    title: Hobbies and Interests
    icon: fas fa-gamepad
    list:
      - hobby: Physical Fitness (Gym)
        icon: fas fa-dumbbell
      - hobby: Cinema and Movies
        icon: fas fa-film
      - hobby: "Reading Books (Favorite: A Fraction of the Whole by Steve Toltz)"
        icon: fas fa-book
      - hobby: Linux Enthusiast (Fedora)
        icon: fab fa-fedora
  contactme:
    title: Contact Me
    icon: fas fa-envelope
    description: >
        Feel free to reach out via email:
        [<i class="fas fa-envelope"></i> shenavar.omid@gmail.com](mailto:shenavar.omid@gmail.com)
  downloadcv:
    title: Download my CV
    icon: fas fa-download
    description: >
        Download my up-to-date CV here:
        [Download CV (PDF)](/cv/CV.pdf)
